### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by ayozeah** [astrofelipe/tesseract#2]
Hello Felipe,

I have used your code in my work. I am publishing an article very soon and I would like to know how to cite "tesseract". I have seen one paper that used it too and the citation was "Rojas et. al, in prep". Is that correct? Thank you in advance.

Cheers,
Ayoze

**Comment by astrofelipe** [comment]
Congratulations!
Yes, for now "Rojas et. al, in prep" and a footnote with the GitHub url would be very helpful too. The paper will be published soon and the readme will be updated with the info
Cheers

**Comment by ayozeah** [comment]
Great, thanks!!!

Cheers,
Ayoze
